[BTAT-11170] SBT upgrade; replace Iteratees dependency
hmrc/mtd-vat-comms pull request #117
Opened 2022-12-22 09:48 UTC by daparkes

Test coverage minimum has been reduced temporarily until we can write integration tests that cover the Iteratees functionality we now have in the service

2022-12-22 11:39 UTC, daparkes commented
https://github.com/hmrc/build-jobs/pull/12356
https://github.com/hmrc/service-manager-config/pull/4859

2022-12-23 15:31 UTC, lewishay requested changes

2022-12-23 15:31 UTC, lewishay commented on app/utils/Iteratee.scala
> +  def fold2[E, A](state: A)(f: (A, E) => Future[(A, Boolean)])(implicit ec: ExecutionContext): Iteratee[E, A] = {
Unused function

2022-12-23 15:31 UTC, lewishay commented on app/utils/Iteratee.scala
> +  def getChunks[E](implicit ec: ExecutionContext): Iteratee[E, List[E]] =
Unused function

2022-12-23 15:31 UTC, lewishay commented on app/utils/Iteratee.scala
> +  def map[B](f: A => B)(implicit ec: ExecutionContext): Iteratee[E, B] = this.flatMap(a => Done(f(a), Input.Empty))
Unused function

2022-12-23 15:31 UTC, lewishay commented on app/utils/Execution.scala
> +  def defaultExecutionContext: ExecutionContext = Implicits.defaultExecutionContext
Unused function

2022-12-23 15:31 UTC, lewishay commented on app/utils/Execution.scala
> +    implicit def trampoline: ExecutionContextExecutor = Execution.Trampoline
Unused function

2022-12-23 15:31 UTC, lewishay commented on app/utils/Enumerator.scala
> +  def apply[E](in: E*): Enumerator[E] = in.length match {
Unused function

2022-12-23 15:31 UTC, lewishay commented on app/utils/Enumerator.scala
> +  def flatten[E](eventuallyEnum: Future[Enumerator[E]])(implicit ec: ExecutionContext): Enumerator[E] = new Enumerator[E] {
Unused function

2022-12-23 15:31 UTC, lewishay commented on app/utils/Enumerator.scala
> +  def empty[E]: Enumerator[E] = new Enumerator[E] {
Unused function after removal of another unused element

2022-12-23 15:31 UTC, lewishay commented on app/utils/Enumerator.scala
> +  private def enumerateSeq[E, A]: (Seq[E], Iteratee[E, A]) => Future[Iteratee[E, A]] = { (l, i) =>
Unused function

2022-12-23 15:31 UTC, lewishay commented on app/utils/Execution.scala
> +    private def executeScheduled(): Unit = local.get match {
You can add the `tailrec` annotation to optimise this (accepting IntelliJ hint will do this automatically)

2022-12-23 15:31 UTC, lewishay commented on app/utils/Iteratee.scala
> +  def pureFoldNoEC[B](folder: Step[E, A] => B)(implicit ec: ExecutionContext): Future[B] =
Unused function

2022-12-23 15:31 UTC, lewishay commented on build.sbt
> +    ScoverageKeys.coverageMinimumStmtTotal := 85,
After removal of all the unused elements above I was able to get slightly above 90% coverage, so can this be bumped to 90? We will still look to play the future IT test story to get it back up to 95.

2023-01-03 13:40 UTC, merged